SELECT EMP_NAME, NVL(DEPT_TITLE, '부서 없음') AS DEPT_TITLE, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE NVL(DEPT_TITLE, '부서 없음') = '인사관리부';

SELECT EMP_NAME, JOB_NAME, SALARY, (SALARY*12) AS ANNUALINCOME
FROM EMPLOYEE
LEFT JOIN JOB USING(JOB_CODE)
WHERE JOB_NAME = '대리'
AND SALARY > 2000000;

SELECT EMP_NAME 이름, 
	TO_CHAR(HIRE_DATE, 'YYYY"년" MM"월" DD"일"') 입사일, 
	DECODE(SUBSTR(EMP_NO,8,1), '1', 'M', '2', 'F') 성별
FROM EMPLOYEE
WHERE HIRE_DATE < TO_DATE('2000-09-06');
                 --> TO_DATE 생략 가능

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
	NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE SALARY > 2000000;

SELECT * FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
	NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE);

SELECT JOB_NAME, ROUND(AVG(SALARY), 1)|| '원' AVG
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
GROUP BY JOB_CODE, JOB_NAME
ORDER BY JOB_CODE
;