-- BASIC SELECT

--1 학과명, 계
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열
FROM TB_DEPARTMENT;

--2 학과 정원
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || ' 명 입니다.' " 학과별 정원"
FROM TB_DEPARTMENT;

--3 국문학과 휴학생 여학생
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='국어국문학과'
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN, 8, 1) = '2';

-- 4. 학번으로 이름 조회
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5. 입학 정원이 20명 이상 30명 이하인 학과 이름과 계열
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6. 
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8. 
SELECT PREATTENDING_CLASS_NO CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT DISTINCT(CATEGORY)
FROM TB_DEPARTMENT;

-- 10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002
AND SUBSTR(STUDENT_ADDRESS, 1, 2) = '전주'
AND ABSENCE_YN = 'N';


-- ADDITIONAL SELECT 
--1.
SELECT STUDENT_NO 학과, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=3;

--3.DECODE(계산식 | 컬럼명, 조건값1, 선택값1, 조건값2, 선택값2..., 아무것도 일치하지 않을 때) 
SELECT PROFESSOR_NAME, TO_DATE('19 || SUBSTR(PROFESSOR_SSN, 1, 2)', 'YY')
FROM TB_PROFESSOR;

--4.
SELECT SUBSTR(PROFESSOR_NAME, 2,4)
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO, STUDENT_NAME, MONTHS_BETWEEN((TO_DATE(SUBSTR(STUDENT_SSN,1,6), 'RRMMDD') AND ENTRANCE_DATE)
FROM TB_STUDENT;

--6.
--7.
--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

--9.
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT POINT
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';

--13.
SELECT 